# This is a basic workflow to help you get started with Actions

name: "Newman Test"
on: [push,pull-request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
        image: postman/newman

  
    steps:
      - name: checkout
        uses: action/checkout@v2
        
      - name: Run API Test
        run: newman run "Lynx Server.postman_collection.json" -e Lynx Server.postman_environment.json 
